config:
  blanks-around-headings:
    # Extra space above level 1/2 headings for better readability
    lines_above: [2, 2, 1, 1, 1, 1]
  fenced-code-language:
    severity: warning
  line-length:
    # Disabled since many doc files have long lines
    enabled: false
  no-duplicate-heading:
    severity: warning
  no-emphasis-as-heading:
    severity: warning
  no-multiple-blanks:
    # For compatibility with the blanks-around-headings setting
    maximum: 2
