include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    use_super_parameters: true
    avoid_print: true
    prefer_relative_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
