name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test

  prepare:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      build_metadata: ${{ steps.vars.outputs.build_metadata }}
      version: ${{ steps.vars.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: vars
        run: |
          build_timestamp=$(date -u +'%Y-%m-%d %H:%M:%S')
          description=$(git describe --long)
          echo "build_metadata=${build_timestamp}-${description}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

  build-android-apk:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build Android APK
        run: >-
          flutter build apk
          --dart-define=BUILD_METADATA='${{ needs.prepare.outputs.build_metadata }}'
          --release
      - name: Prepare Android APK
        run: cp build/app/outputs/flutter-apk/app-release.apk unitary-${{ needs.prepare.outputs.version }}.apk
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: unitary-${{ needs.prepare.outputs.version }}.apk

  build-web:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.x'
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build web
        run: >-
          flutter build web
          --dart-define=BUILD_METADATA='${{ needs.prepare.outputs.build_metadata }}'
          --release
          --wasm
      - name: Prepare web build
        run: zip -r unitary-${{ needs.prepare.outputs.version }}-web.zip build/web
      - uses: actions/upload-artifact@v4
        with:
          name: web-zip
          path: unitary-${{ needs.prepare.outputs.version }}-web.zip

  release:
    needs: [prepare, build-android-apk, build-web]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/download-artifact@v4
        with:
          name: android-apk
      - uses: actions/download-artifact@v4
        with:
          name: web-zip
      - name: Read release notes
        run: >-
          git tag -l --format="%(contents:body)" ${{ github.ref_name }} | tee RELEASE_NOTES.md
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release create ${{ github.ref_name }}
          --notes-file RELEASE_NOTES.md
          --title "Release ${{ needs.prepare.outputs.version }}"
          unitary-${{ needs.prepare.outputs.version }}.apk
          unitary-${{ needs.prepare.outputs.version }}-web.zip
